version: '3.6'
services:
  sut:
     build:
       context: .
       dockerfile: Dockerfile-Test

     volumes:
        - ./test:/home/sage/test:ro
        - ./artifacts:/books/artifacts
        #- ./helpers:/opt/.pycharm_helpers/pycharm:ro
